version: '1.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/app
    environment:
      STAGE: dev

    networks:
      - auth-network
    depends_on:
      - mysql

  mysql:
    image: mysql:9.0.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./env/db.env
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
